dist: focal

language: c

cache:
  - pip
  - ccache

addons:
  apt:
    packages:
    - shellcheck
    - valgrind
    - python-docutils
    - python3-pip
    - python3-setuptools
    - ninja-build
    - meson
    - python3-pytest
    - libglib2.0-dev
    - ccache

install: test/travis-install.sh

jobs:
  include:
    - name: Lint
      script: ./test/lint.sh
      install: skip
    - name: Build + Test (clang)
      compiler: clang
      script: test/travis-build.sh
    - name: Build + Test (gcc)
      compiler: gcc
      script: test/travis-build.sh
    - name: Build with sanitizer (undefined)
      compiler: clang
      env: SANITIZER=undefined
      script: test/travis-build.sh
    - name: Build with sanitizer (address)
      compiler: clang
      env: SANITIZER=address
      script: test/travis-build.sh
